// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuestionBank.Infrastructure.Implementation.DataAccess;

#nullable disable

namespace QuestionBank.Infrastructure.Implementation.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260124204701_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("QuestionBank")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuestionBank.Domain.CodingQuestionLanguageLimit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CodingQuestionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid");

                    b.Property<int>("MemoryLimitMb")
                        .HasColumnType("integer");

                    b.Property<int>("TimeLimitMs")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CodingQuestionId");

                    b.HasIndex("LanguageId");

                    b.ToTable("CodingQuestionLanguageLimits", "QuestionBank");
                });

            modelBuilder.Entity("QuestionBank.Domain.Competency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Competencies", "QuestionBank");
                });

            modelBuilder.Entity("QuestionBank.Domain.CompetencyMatrix", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GradeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SpecializationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SpecializationId");

                    b.HasIndex("GradeId", "SpecializationId")
                        .IsUnique();

                    b.ToTable("CompetencyMatrices", "QuestionBank");
                });

            modelBuilder.Entity("QuestionBank.Domain.CompetencyMatrixItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompetencyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CompetencyMatrixId")
                        .HasColumnType("uuid");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("CompetencyId");

                    b.HasIndex("CompetencyMatrixId");

                    b.ToTable("CompetencyMatrixItems", "QuestionBank");
                });

            modelBuilder.Entity("QuestionBank.Domain.Grade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Grades", "QuestionBank");
                });

            modelBuilder.Entity("QuestionBank.Domain.InterviewPreset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GradeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SpecializationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GradeId");

                    b.HasIndex("SpecializationId");

                    b.ToTable("InterviewPresets", "QuestionBank");
                });

            modelBuilder.Entity("QuestionBank.Domain.InterviewPresetTechnology", b =>
                {
                    b.Property<Guid>("InterviewPresetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TechnologyId")
                        .HasColumnType("uuid");

                    b.HasKey("InterviewPresetId", "TechnologyId");

                    b.HasIndex("TechnologyId");

                    b.ToTable("InterviewPresetTechnologies", "QuestionBank");
                });

            modelBuilder.Entity("QuestionBank.Domain.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompetencyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GradeId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReferenceSolution")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TechnologyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompetencyId");

                    b.HasIndex("GradeId");

                    b.HasIndex("TechnologyId");

                    b.ToTable("Questions", "QuestionBank");
                });

            modelBuilder.Entity("QuestionBank.Domain.Specialization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Specializations", "QuestionBank");
                });

            modelBuilder.Entity("QuestionBank.Domain.Technology", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Technologies", "QuestionBank");
                });

            modelBuilder.Entity("QuestionBank.Domain.TestCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CodingQuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExpectedOutput")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Input")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CodingQuestionId");

                    b.ToTable("TestCases", "QuestionBank");
                });

            modelBuilder.Entity("QuestionBank.Domain.CodingQuestionLanguageLimit", b =>
                {
                    b.HasOne("QuestionBank.Domain.Question", "CodingQuestion")
                        .WithMany("LanguageLimits")
                        .HasForeignKey("CodingQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuestionBank.Domain.Technology", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CodingQuestion");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("QuestionBank.Domain.CompetencyMatrix", b =>
                {
                    b.HasOne("QuestionBank.Domain.Grade", "Grade")
                        .WithMany()
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuestionBank.Domain.Specialization", "Specialization")
                        .WithMany()
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grade");

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("QuestionBank.Domain.CompetencyMatrixItem", b =>
                {
                    b.HasOne("QuestionBank.Domain.Competency", "Competency")
                        .WithMany()
                        .HasForeignKey("CompetencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuestionBank.Domain.CompetencyMatrix", null)
                        .WithMany("Competencies")
                        .HasForeignKey("CompetencyMatrixId");

                    b.Navigation("Competency");
                });

            modelBuilder.Entity("QuestionBank.Domain.InterviewPreset", b =>
                {
                    b.HasOne("QuestionBank.Domain.Grade", "Grade")
                        .WithMany()
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuestionBank.Domain.Specialization", "Specialization")
                        .WithMany()
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grade");

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("QuestionBank.Domain.InterviewPresetTechnology", b =>
                {
                    b.HasOne("QuestionBank.Domain.InterviewPreset", "InterviewPreset")
                        .WithMany("Technologies")
                        .HasForeignKey("InterviewPresetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuestionBank.Domain.Technology", "Technology")
                        .WithMany()
                        .HasForeignKey("TechnologyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InterviewPreset");

                    b.Navigation("Technology");
                });

            modelBuilder.Entity("QuestionBank.Domain.Question", b =>
                {
                    b.HasOne("QuestionBank.Domain.Competency", "Competency")
                        .WithMany()
                        .HasForeignKey("CompetencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuestionBank.Domain.Grade", "Grade")
                        .WithMany()
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuestionBank.Domain.Technology", "Technology")
                        .WithMany()
                        .HasForeignKey("TechnologyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competency");

                    b.Navigation("Grade");

                    b.Navigation("Technology");
                });

            modelBuilder.Entity("QuestionBank.Domain.TestCase", b =>
                {
                    b.HasOne("QuestionBank.Domain.Question", "CodingQuestion")
                        .WithMany("TestCases")
                        .HasForeignKey("CodingQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CodingQuestion");
                });

            modelBuilder.Entity("QuestionBank.Domain.CompetencyMatrix", b =>
                {
                    b.Navigation("Competencies");
                });

            modelBuilder.Entity("QuestionBank.Domain.InterviewPreset", b =>
                {
                    b.Navigation("Technologies");
                });

            modelBuilder.Entity("QuestionBank.Domain.Question", b =>
                {
                    b.Navigation("LanguageLimits");

                    b.Navigation("TestCases");
                });
#pragma warning restore 612, 618
        }
    }
}
