name: CI/CD Pipeline

on:
  push:
    branches: [master]

jobs:
  compose-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and start services
        run: docker compose up -d --build

      - name: Run integration tests (Postman)
        run: |
          npm install -g newman
          newman run postman/integration-tests.json \
            -e postman/ci-env.json

      - name: Shutdown services
        if: always()
        run: docker compose down
